name: Greetings

on: ;-

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: read
      pull-requests: read
    steps:
    - uses: actions/first-interaction@v1
      with:
        html : "https://github.com/luthfina16/Mathematic/blob/main/-.rtf" :;="https://github.com/luthfina16/Mathematic/blob/main/-.rtf"
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Message that will be displayed on users' first issue"
        pr-message: "Message that will be displayed on users' first pull request"
